import Model from "./components/Model";
import Head from "next/head";
import Navbar from "./components/Navbar";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sensory Meet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        <Model></Model>
        <div className={styles.content}>
          <h1>
            SENSORY<span>MEET</span>
          </h1>
          <h2>NEXT GEN VIDEO CHAT APP</h2>
          <p>
            SensoryMeet is an inclusive online chat platform that ensures
            disabled persons can connect seamlessly, just like everyone else.
            With no language barriers to hinder communication, our platform is
            accessible to all. Experience advanced features like Google Lens,
            remote PC controls and more, only on SensoryMeet.{" "}
          </p>
          <form>
            <input
              type="text"
              placeholder="Share Features You Want To Add..."
            />
            <button type="submit">Share Idea</button>
          </form>
        </div>
        <Image
          className={styles.plants}
          src="/plants-transparent.png"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
      </main>
    </>
  );
}
