import Head from "next/head";
import Navbar from "./components/Navbar";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { useSocket } from "./context/SocketProvider";
import { useRouter } from "next/router";
import { v4 as uuidv4 } from 'uuid';

export default function Home() {

  const [ name, setName ] = useState("")
  const socket = useSocket()
  const router = useRouter();

  const handleFormSubmission = useCallback((e) => {
    e.preventDefault()
    socket.emit("room:join", { name })
  }, [name])

  const handleRoomJoin = useCallback((data) => {
    const { name } = data
    const roomId = uuidv4()
    console.log(roomId)
    router.push(`/room/${roomId}`, `/room/${roomId}`);
  }, [])

  useEffect(() => {
    socket.on("room:join", handleRoomJoin)
    return () => socket.off("room:join")
  }, [socket, handleRoomJoin])

  return (
    <>
      <Head>
        <title>Sensory Meet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        <div className={styles.content}>
          <h1>
            SENSORY<span>MEET</span>
          </h1>
          <h2>NEXT GEN VIDEO CHAT APP</h2>
          <p>
            SensoryMeet is an inclusive online chat platform that ensures
            disabled persons can connect seamlessly, just like everyone else.
            With no language barriers to hinder communication, our platform is
            accessible to all. Experience advanced features like Google Lens,
            remote PC controls and more, only on SensoryMeet.{" "}
          </p>
          <form onSubmit={handleFormSubmission}>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Enter Your Name" />
            <button type="submit">New Meeting</button>
          </form>
        </div>
        <Image
          className={styles.plants}
          src="/plants-transparent.png"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
      </main>
    </>
  );
}
